"""Screening History

Revision ID: 5913a03f3268
Revises: 89c303cdc0a9
Create Date: 2025-12-18 22:30:39.440399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5913a03f3268'
down_revision: Union[str, Sequence[str], None] = '89c303cdc0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screening_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_history_id'), 'screening_history', ['id'], unique=False)
    op.create_index(op.f('ix_screening_history_user_id'), 'screening_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_history_user_id'), table_name='screening_history')
    op.drop_index(op.f('ix_screening_history_id'), table_name='screening_history')
    op.drop_table('screening_history')
    # ### end Alembic commands ###
