"""Update user table to make fields required

Revision ID: a42d987189ed
Revises: fb22f0433edb
Create Date: 2025-12-19 16:49:42.236686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a42d987189ed'
down_revision: Union[str, Sequence[str], None] = 'fb22f0433edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'gender',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'height_m',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('user', 'weight_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('user', 'is_asian',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_asian',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'weight_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('user', 'height_m',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('user', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'gender',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
