"""add_xai_plots_to_screening_history

Revision ID: be7f74c32e17
Revises: 64f7968b4a40
Create Date: 2025-12-21 02:28:07.129496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be7f74c32e17'
down_revision: Union[str, Sequence[str], None] = '64f7968b4a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screening_history', sa.Column('waterfall_plot', sa.LargeBinary(), nullable=True))
    op.add_column('screening_history', sa.Column('force_plot', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_history', 'force_plot')
    op.drop_column('screening_history', 'waterfall_plot')
    # ### end Alembic commands ###
