"""Update user table

Revision ID: fb22f0433edb
Revises: 5913a03f3268
Create Date: 2025-12-19 12:12:25.666219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb22f0433edb'
down_revision: Union[str, Sequence[str], None] = '5913a03f3268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('screening_history', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.add_column('user', sa.Column('gender', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('height_m', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('is_asian', sa.Boolean(), nullable=True))
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_user_age'), 'user', ['age'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_age'), table_name='user')
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'is_asian')
    op.drop_column('user', 'weight_kg')
    op.drop_column('user', 'height_m')
    op.drop_column('user', 'age')
    op.drop_column('user', 'gender')
    op.alter_column('screening_history', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
